# Generated by Django 3.2 on 2021-05-03 10:48

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin_Register',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(8)], verbose_name='password')),
                ('group', models.CharField(blank=True, default='admin', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=200)),
                ('msg', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor_Register',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('username', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(8)], verbose_name='password')),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=10)),
                ('group', models.CharField(blank=True, default='doctor', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('frontimg', models.ImageField(default='', upload_to='product/images/frontimg')),
                ('img1', models.ImageField(upload_to='product/images/img1')),
                ('img2', models.ImageField(upload_to='product/images/img2')),
                ('img3', models.ImageField(upload_to='product/images/img3')),
                ('img4', models.ImageField(upload_to='product/images/img4')),
                ('prod_name', models.CharField(max_length=100, unique=True)),
                ('prod_price', models.FloatField()),
                ('prod_detail', models.CharField(max_length=300)),
                ('prod_content', models.CharField(max_length=100)),
                ('featured', models.BooleanField(default=False)),
                ('latest', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='User_Profile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('photo', models.ImageField(default='', upload_to='profile_photos')),
                ('fullname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=200)),
                ('username', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
