# Generated by Django 3.2 on 2021-05-08 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('final_app', '0005_auto_20210508_1410'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='customer',
            new_name='username',
        ),
    ]
