# Generated by Django 3.2 on 2021-05-11 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('final_app', '0007_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor_register',
            name='username',
            field=models.CharField(max_length=200),
        ),
    ]
