# Generated by Django 3.2 on 2021-05-13 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('final_app', '0009_appointment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='message',
            new_name='msg',
        ),
    ]
