# Generated by Django 3.2 on 2021-05-21 09:24

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('final_app', '0012_appointment_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donate',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dnr_name', models.CharField(max_length=200)),
                ('dnr_address', models.CharField(max_length=200)),
                ('dnr_phone', models.CharField(max_length=10)),
                ('drg_name', models.CharField(max_length=100)),
                ('drg_lotno', models.CharField(max_length=20)),
                ('drg_exdate', models.DateField(default=datetime.datetime.today)),
                ('drg_quantity', models.IntegerField()),
                ('drg_strength', models.CharField(max_length=10)),
                ('signature', models.ImageField(upload_to='signatures')),
                ('today_date', models.DateField(default=datetime.datetime.today)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
