# Generated by Django 5.2.8 on 2025-11-16 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("final_app", "0014_alter_user_profile_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user_profile",
            name="photo",
            field=models.ImageField(
                default="profile_phots/default.jpg", upload_to="profile_photos"
            ),
        ),
    ]
